# FL Coordinator Service
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    app: fl
spec:
  ports:
  - port: 50050
  selector:
    app: fl
  type: ClusterIP
---
kind: Pod
apiVersion: v1
metadata:
  name: coordinator-0
  labels:
    app: fl
spec:
  containers:
  - image: fedota/fl-coordinator
    name: fl-coordinator
    imagePullPolicy: IfNotPresent
    env:
    - name: CHECKIN_LIMIT
      value: "1"
    - name: FL_ROOT_PATH
      value: "/mnt"
    - name: PROBLEM_ID
      valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
    ports:
    - containerPort: 50050
    volumeMounts:
    - name: fl-pvc
      mountPath: "/mnt"
  volumes:
  - name: fl-pvc
    persistentVolumeClaim:
      claimName: fl-pvc
