# Claim the fl pv
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fl-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
