# PV using NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fl-pv
  labels:
    fl-problem: pb0
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # NFS server is exposed through a service named nfs-service 
    server: nfs-service.default.svc.cluster.local
    path: "/pb0"